server:
  port: 8080

spring:
  application:
    name: tevsgateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: statusserver-route
          uri: lb://statusserver
          predicates:
            - Path=/status/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8090/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org:
      springframework:
        web: DEBUG
      cloud:
        gateway: DEBUG
    com:
      netflix:
        discovery: DEBUG