server:
  port: 8080

spring:
  application:
    name: tevsgateway
  cloud:
    loadbalancer:
      retry:
        enabled: true
      cache:
        enabled: false
    gateway:
      httpclient:
        connect-timeout: 2000
        response-timeout: 3s
      discovery:
        locator:
          enabled: true
      routes:
        - id: statusserver-route
          uri: lb://statusserver
          predicates:
            - Path=/status/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    eureka-service-url-poll-interval-seconds: 2
    registry-fetch-interval-seconds: 2

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org:
      springframework:
        web: DEBUG
      cloud:
        gateway: DEBUG
    com:
      netflix:
        discovery: INFO