server:
  port: 0

spring:
  application:
    name: statusserver
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ${KAFKA_GROUP_ID:statusserver-${random.value}}

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.int}
  client:
    register-with-eureka: true
    fetch-registry: false
    healthcheck:
      enabled: true
#    serviceUrl:
#      defaultZone: http://localhost:8090/eureka

logging:
  level:
    org:
      springframework:
        web: DEBUG
      cloud:
        gateway: DEBUG
    com:
      netflix:
        discovery: ERROR