server:
  port: 0

spring:
  application:
    name: statusserver
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
  jackson:
    serialization:
      indent-output: true

eureka:
  instance:
    # leaseRenewalIntervalInSeconds: 10  # optional: Häufigkeit der Heartbeats
    # leaseExpirationDurationInSeconds: 30 # optional: Ablaufzeit
    instance-id: ${spring.application.name}:${random.int}
    # nonSecurePortEnabled: true
    # nonSecurePort: ${server.port}
  client:
    register-with-eureka: true
    fetch-registry: false
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8090/eureka