server:
  port: 8091

spring:
  application:
    name: statusserver
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ${KAFKA_GROUP_ID:statusserver-${random.value}}
      heartbeat-interval: 3000
      properties:
        session.timeout.ms: 5000

eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    initial-status: up
    health-check-url-path: /actuator/health
    status-page-url-path: /actuator/info
  client:
    register-with-eureka: true
    fetch-registry: false
    healthcheck:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org:
      springframework:
        web: ERROR
      cloud:
        gateway: ERROR
    com:
      netflix:
        discovery: ERROR
    fh:
      bswe:
        statusserver: DEBUG
    root: info
