server:
  port: 0

spring:
  application:
    name: statusserver
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ${KAFKA_GROUP_ID:statusserver-${random.value}}

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.int}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    register-with-eureka: true
    fetch-registry: false
    healthcheck:
      enabled: true


logging:
  level:
    org:
      springframework:
        web: ERROR
      cloud:
        gateway: ERROR
    com:
      netflix:
        discovery: ERROR
    fh:
      bswe:
        statusserver: DEBUG
    root: info
